services:
  tlsn-verifier:
    container_name: tlsn-verifier
    image: docker.io/rbbozkurt/tlsn-verifier:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    platform: linux/amd64
    environment:
      - TLSN_VERIFIER_API_KEY
      - TLSN_VERIFIER_HOST
      - TLSN_VERIFIER_PORT
      - TLSN_VERIFIER_ACCEPTED_SERVER_NAMES
      - TLSN_VERIFIER_ACCEPTED_VERSION
