services:
  tlsn-verifier:
    container_name: tlsn-verifier
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    platform: linux/amd64
